language: python
python:
  - '3.5'
install:
  - sudo locale-gen "lv_LV.utf8"
  - touch zibenitis/secret_key
  - echo testkey > zibenitis/secret_key
  - pip install -r requirements.txt
script:
  - python manage.py test
