#!/bin/bash

REPOS=/home/www/zibenitis

# force lock for single script executing
LOCK="/tmp/update"

lockfile-create $LOCK

cd $REPOS && git pull

python3 manage.py makemigrations
python3 manage.py migrate

scss static-loc/scss/style.scss static-loc/style.css
python3 manage.py collectstatic --noinput

chown -R www-data:www-data $REPOS
/etc/init.d/apache2 restartd


lockfile-remove $LOCK

